"""Auxiliary per-camera 2D refinement head (Phase 1 A1, plug-in module).

Ported from chenxi/onemodel ``projects/mmdet3d_plugin/sparse/oe/refine_2d.py``
(2026-05-15 commit 577baad) to Sparse4D-V3 baseline codebase. Original logic
preserved verbatim except for:
  - registry: ``SPARSE_MODULES`` -> mmcv ``PLUGIN_LAYERS``
  - helper: ``Scale`` defined inline (chenxi puts it in their blocks.py)
  - helper: ``linear_relu_ln`` imported from our own ``.blocks``
  - head class name in docstrings: ``SparseBEVOEHead`` -> ``Sparse4DHead``

This module wires into ``Sparse4DHead`` via the generic ``aux_modules``
hook protocol — ``head.py`` exposes two callback points:

    after_decoder(ctx, output)   # at the end of head.forward
    after_loss(ctx, output)      # at the end of head.loss

This class implements both. ``head.py`` itself contains zero references
to refine2d / 2D supervision; all bookkeeping lives here.

How it samples image features (no changes to head.py / blocks.py):

* takes the *final* anchor (from ``ctx['anchor']``) and projects each
  anchor centre into every camera using the raw ``lidar2img`` matrix
  (``ctx['projection_mat_raw']``);
* bilinearly samples a single image feature at each projected centre
  from the chosen FPN level (``ctx['feature_maps'][self.level_index]``).
  This does NOT touch the head's deformable / keypoint sampling path —
  it is a one-time, cheap re-sample per anchor;
* per-cam features + anchor embedding feed a small MLP that predicts
  ``(dx, dy, log_w, log_h)`` offsets relative to the projected centre,
  scaled by ``box_mult_ratio`` (default 32, matches s32 FPN stride);
* a parallel MLP predicts ``num_cls`` sigmoid logits per (cam, anchor).

Loss:

* 2D GT boxes are auto-generated by projecting the matched 3D GT's
  eight corners into each camera and taking min/max of the
  in-front-of-camera, in-image corners — no extra 2D annotation
  required.
* Visibility: ``>=4 corners in front of cam AND projected rect
  overlaps the image rect``.
* ``loss_2d_box_{last_decoder_idx}`` / ``loss_2d_cls_{last_decoder_idx}``
  are emitted UNCONDITIONALLY (even when zero valid samples exist,
  via a zero placeholder). This keeps the loss-key set deterministic
  across DDP ranks so ``mmcv._parse_losses`` never trips.
"""
import warnings
from typing import List, Optional, Sequence, Tuple

import torch
import torch.nn as nn
import torch.nn.functional as F
from mmcv.cnn import bias_init_with_prob
from mmcv.cnn.bricks.registry import PLUGIN_LAYERS
from mmdet.core.bbox.iou_calculators import bbox_overlaps
from mmdet.models.builder import build_loss

from .blocks import linear_relu_ln

__all__ = ['SparseBox2DRefinement']


class Scale(nn.Module):
    """Learnable scalar multiplier (used to scale predicted offsets).

    Copied from chenxi/onemodel blocks.py to keep refine_2d.py self-contained
    (avoid polluting Sparse4D's shared blocks.py with trick-specific helpers).
    """

    def __init__(self, scale: float = 1.0):
        super().__init__()
        self.scale = nn.Parameter(torch.tensor(scale, dtype=torch.float))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return x * self.scale


def _reduce_mean(x):
    """All-reduce a scalar across DDP world, return the per-rank mean."""
    if not torch.is_tensor(x):
        x = torch.tensor(x, dtype=torch.float32)
    try:
        import torch.distributed as dist
        if dist.is_available() and dist.is_initialized():
            x = x.clone()
            dist.all_reduce(x.div_(dist.get_world_size()))
    except Exception:
        pass
    return x


@PLUGIN_LAYERS.register_module()
class SparseBox2DRefinement(nn.Module):
    """Per-camera 2D bbox + cls refinement, attached to ``Sparse4DHead``
    through the ``aux_modules`` hook (no head.py modifications required).

    Args:
        embed_dims: feature dim of the sampled per-cam embedding.
        num_cls: # detection classes (sigmoid head).
        box_mult_ratio: stride-aligned scale applied to predicted
            ``(dx, dy, exp(log_wh))`` offsets. Default 32 ≈ s32 FPN.
        level_index: which entry of ``feature_maps`` to sample. Use
            the same level the OD deformable branch samples from
            (e.g. 2 for a 3-level FPN with strides [8, 16, 32]).
        with_cls_branch: emit a per-cam classification head.
        loss_cls2d / loss_bbox2d: standard mmdet loss configs
            (built with ``mmdet.build_loss``).
        loss_weight: extra multiplier applied on TOP of the loss
            module's own ``loss_weight`` — leave at 1.0 unless you
            need a quick lever to tune total contribution.
        class_loss_weights: per-class scalar reweighting applied to
            BOTH the cls and box auxiliary losses, indexed by the
            3D-matched class label (the same label space as the
            sparse_od_head's main cls target). When ``None`` (default)
            an all-ones buffer is registered so the loss pipeline is
            mathematically unchanged from the un-weighted baseline.

            Normalisation uses the *weighted* sum of per-anchor
            weights as the avg_factor / num_pos denominator (Option X)
            so doubling every entry is a no-op for the total refine2d
            loss magnitude — only RELATIVE weighting between classes
            matters. This keeps the multi-task CAGrad balance intact
            (refine2d's slice of the total loss stays the same; the
            internal allocation between classes shifts).

            Concrete usage — derived empirically from the 7-point iter
            sweep {base, 1k, 2k, 3k, 4k, 5k, 10k} on the highlr 2k
            recipe (see commit log on cx/dev for the trajectory):

            * other_vehicle (idx 2) shows an inverted-U peaking at 2k
              (+0.345 mAP vs base) and decaying to a +0.108 plateau
              by 10k. Boosting it (3.0x) keeps the 2D supervision
              alive on this class as longer schedules let other
              classes' monotonic gains accumulate.
            * van (idx 4) shows a weaker inverted-U (peak +0.104 at
              1k, decaying to +0.030 at 10k). 2.0x is enough.
            * Everything else is either early-saturated, noisy-flat,
              or monotonic-rise — leave at 1.0 so the new schedule
              does not starve them.

            Only the ``gt_source='project'`` (and `real`/`hybrid`)
            loss path applies these weights. ``real_simota`` uses its
            own SimOTA-based assignment + normalisation in
            ``_run_simota_branch`` and currently IGNORES this kwarg
            (a warning is emitted at construction time so the
            mismatch isn't silent).
    """

    # NOTE: keep this class registry-buildable through PLUGIN_LAYERS so
    # configs can pass it as a {type:..., ...} dict to ``head.aux_modules``.

    def __init__(
        self,
        embed_dims: int = 256,
        num_cls: int = 10,
        box_mult_ratio: float = 32.0,
        level_index: int = 2,
        with_cls_branch: bool = True,
        loss_cls2d=None,
        loss_bbox2d=None,
        loss_weight: float = 1.0,
        gt_source: str = 'project',
        gt_match_iou_thr: float = 0.3,
        gt_bboxes_key: str = 'gt_bboxes',
        gt_labels_key: str = 'gt_labels',
        # SimOTA dynamic-k matching parameters (only used when
        # ``gt_source='real_simota'``). Mirrors ws-onemodel-dev's
        # ``SparseBEVOEHead._assign_2d_simota``: per-(batch, cam) we
        # build a pairwise-IoU cost between *all* anchor predictions
        # and the per-cam real 2D GT list, then run dynamic-k to pick
        # positives. ``candidate_topk`` controls the per-GT IoU
        # summation window that decides each GT's dynamic k.
        simota_topk: int = 5,
        simota_eps: float = 1e-7,
        # Prior probability for the focal-loss-style cls bias init. mmdet
        # convention is 0.01 (bias=-4.595) for dense heads. Bumping to
        # e.g. 0.1 (bias=-2.197) increases the early focal-loss gradient
        # signal — useful when refine2d is starved for optimizer steps
        # by the multi-task CAGrad schedule.
        cls_prior_prob: float = 0.01,
        # Per-class loss reweighting (see class docstring for full
        # rationale + the empirical 7-point trajectory it's derived
        # from). When ``None`` (default) registers an all-ones buffer,
        # so the loss pipeline is bit-identical to the un-weighted
        # baseline. When given, must be a length-``num_cls`` sequence
        # of non-negative floats indexed in the OD class order.
        class_loss_weights: Optional[Sequence[float]] = None,
    ):
        super().__init__()
        self.embed_dims = embed_dims
        self.num_cls = num_cls
        self.box_mult_ratio = float(box_mult_ratio)
        self.level_index = int(level_index)
        self.with_cls_branch = with_cls_branch
        self.loss_weight = float(loss_weight)
        assert gt_source in ('project', 'real', 'hybrid', 'real_simota'), (
            f'gt_source must be one of project/real/hybrid/real_simota, '
            f'got {gt_source}'
        )
        self.gt_source = gt_source
        self.gt_match_iou_thr = float(gt_match_iou_thr)
        self.gt_bboxes_key = gt_bboxes_key
        self.gt_labels_key = gt_labels_key
        self.simota_topk = int(simota_topk)
        self.simota_eps = float(simota_eps)
        cls_prior_prob = float(cls_prior_prob)
        assert 0.0 < cls_prior_prob < 1.0, (
            f'cls_prior_prob must be in (0, 1), got {cls_prior_prob}')
        self._cls_prior_prob = cls_prior_prob

        # --- per-class loss weight buffer -----------------------------
        # Always materialise to a length-``num_cls`` float32 buffer so
        # the gather op in ``after_loss`` is unconditional (no Python
        # branch in the hot path). When the user passes ``None`` the
        # buffer is all-ones; the gather + weighted-mean code path is
        # then a no-op vs the un-weighted baseline.
        #
        # ``persistent=False`` keeps the buffer OUT of ``state_dict()``
        # so a ckpt trained with one weight vector can be reloaded
        # under a DIFFERENT weight vector cleanly — the weights are
        # hyperparameters of the loss, not learned state, and would
        # silently override the new cfg's choice if we let them ride
        # in the ckpt.
        if class_loss_weights is None:
            _cw: List[float] = [1.0] * num_cls
        else:
            assert len(class_loss_weights) == num_cls, (
                f'class_loss_weights length {len(class_loss_weights)} '
                f'!= num_cls {num_cls}'
            )
            _cw = [float(x) for x in class_loss_weights]
            assert all(x >= 0.0 for x in _cw), (
                f'class_loss_weights must all be >= 0, got {_cw}'
            )
            if gt_source == 'real_simota':
                warnings.warn(
                    'class_loss_weights is IGNORED when '
                    'gt_source="real_simota" (the SimOTA branch has '
                    'its own assignment + normalisation in '
                    '_run_simota_branch). Either switch to '
                    "gt_source='project' / 'real' / 'hybrid' or "
                    'extend _run_simota_branch to apply the weights.',
                    stacklevel=2,
                )
        self.register_buffer(
            '_class_loss_weights',
            torch.tensor(_cw, dtype=torch.float32),
            persistent=False,
        )

        self.layers = nn.Sequential(
            *linear_relu_ln(embed_dims, 2, 2),
            nn.Linear(embed_dims, 4),
            Scale(1.0),
        )
        if with_cls_branch:
            self.cls_layers = nn.Sequential(
                *linear_relu_ln(embed_dims, 1, 2),
                nn.Linear(embed_dims, num_cls),
            )
        else:
            self.cls_layers = None

        self.loss_cls2d = (
            build_loss(loss_cls2d) if isinstance(loss_cls2d, dict)
            else loss_cls2d
        )
        self.loss_bbox2d = (
            build_loss(loss_bbox2d) if isinstance(loss_bbox2d, dict)
            else loss_bbox2d
        )

    def init_weight(self) -> None:
        """Called by ``SparseBEVOEHead.init_weights`` (which walks every
        sub-module and invokes ``init_weight`` when present)."""
        if self.with_cls_branch:
            bias_init = bias_init_with_prob(self._cls_prior_prob)
            nn.init.constant_(self.cls_layers[-1].bias, bias_init)

    # ------------------------------------------------------------------
    # Geometry helpers (pixel space, raw lidar2img)
    # ------------------------------------------------------------------
    @staticmethod
    def _project_anchor_center(anchor_xyz, projection_mat):
        """Project (B, A, 3) lidar-frame anchor centres to each cam.

        Returns:
            xy_pixel: (B, V, A, 2) pixel coords (un-normalised).
            valid:    (B, V, A) bool, depth > 0.1 m.
        """
        bs, num_anchor = anchor_xyz.shape[:2]
        ones = anchor_xyz.new_ones((bs, num_anchor, 1))
        pts = torch.cat([anchor_xyz, ones], dim=-1)
        pts = pts[:, None, :, :, None]
        proj = projection_mat[:, :, None]
        out = (proj @ pts).squeeze(-1)
        depth = out[..., 2:3]
        depth_safe = torch.clamp(depth, min=1e-5)
        xy = out[..., :2] / depth_safe
        valid = depth.squeeze(-1) > 0.1
        return xy, valid

    @staticmethod
    def _build_3d_corners(center, size, sin_yaw, cos_yaw):
        """(B, A, 3) + (B, A, 3) + 2x(B, A, 1) → (B, A, 8, 3) box corners."""
        signs = center.new_tensor([
            [-1, -1, -1], [-1, -1, +1], [-1, +1, -1], [-1, +1, +1],
            [+1, -1, -1], [+1, -1, +1], [+1, +1, -1], [+1, +1, +1],
        ]) * 0.5
        local = signs[None, None] * size[..., None, :]
        cy = cos_yaw[..., None]
        sy = sin_yaw[..., None]
        x = local[..., 0:1] * cy - local[..., 1:2] * sy
        y = local[..., 0:1] * sy + local[..., 1:2] * cy
        z = local[..., 2:3]
        rotated = torch.cat([x, y, z], dim=-1)
        return rotated + center[..., None, :]

    @staticmethod
    def _project_corners(corners, projection_mat):
        """(B, A, 8, 3) + (B, V, 4, 4) → (B, V, A, 8, 2) pixel, (B, V, A, 8) depth."""
        ones = corners.new_ones(corners.shape[:-1] + (1,))
        pts = torch.cat([corners, ones], dim=-1)
        pts_e = pts[:, None, :, :, :, None]
        proj = projection_mat[:, :, None, None]
        out = (proj @ pts_e).squeeze(-1)
        depth = out[..., 2]
        depth_safe = torch.clamp(depth, min=1e-5)
        pix_xy = out[..., :2] / depth_safe[..., None]
        return pix_xy, depth

    # ------------------------------------------------------------------
    # Feature sampling (no deformable / keypoint complexity)
    # ------------------------------------------------------------------
    def _sample_per_cam_features(self, feat_map, xy_pixel, image_wh):
        """Bilinearly sample one image-feature vector at each (cam, anchor)
        location.

        Args:
            feat_map: (B*V, C, H_feat, W_feat) or (B, V, C, H_feat, W_feat).
            xy_pixel: (B, V, A, 2) in input image pixel coords.
            image_wh: (B, V, 2) — (W, H) of the input image plane that
                ``xy_pixel`` is in.

        Returns:
            (B, V, A, C) sampled embeddings.
        """
        if feat_map.dim() == 5:
            B, V = feat_map.shape[:2]
            feat_map = feat_map.flatten(0, 1)
        bs, num_cams, num_anchor, _ = xy_pixel.shape
        C = feat_map.shape[1]

        W = image_wh[..., 0:1].unsqueeze(2)
        H = image_wh[..., 1:2].unsqueeze(2)
        x_norm = (xy_pixel[..., 0:1] / W) * 2.0 - 1.0
        y_norm = (xy_pixel[..., 1:2] / H) * 2.0 - 1.0
        grid = torch.cat([x_norm, y_norm], dim=-1)
        grid = grid.view(bs * num_cams, num_anchor, 1, 2)

        sampled = F.grid_sample(
            feat_map.float(), grid.float(),
            mode='bilinear', padding_mode='zeros', align_corners=False,
        )
        sampled = sampled.squeeze(-1).permute(0, 2, 1)
        return sampled.view(bs, num_cams, num_anchor, C)

    def _bbox_decode(self, priors_xy, bbox_offsets):
        """priors_xy: (..., 2) px; bbox_offsets: (..., 4) → tlbr px."""
        xy = bbox_offsets[..., :2] * self.box_mult_ratio + priors_xy
        wh = bbox_offsets[..., 2:].exp() * self.box_mult_ratio
        tl = xy - wh / 2.0
        br = xy + wh / 2.0
        return torch.cat([tl, br], dim=-1)

    # ------------------------------------------------------------------
    # ctx helpers
    # ------------------------------------------------------------------
    @staticmethod
    def _infer_image_wh(metas, device, dtype, bs, num_cams):
        """Best-effort recovery of per-cam (W, H) from ``metas``."""
        image_wh = metas.get('image_wh', None)
        if image_wh is None:
            img_t = metas.get('img', None)
            if torch.is_tensor(img_t):
                if img_t.dim() == 5:
                    _, _, _, Himg, Wimg = img_t.shape
                elif img_t.dim() == 4:
                    _, _, Himg, Wimg = img_t.shape
                else:
                    Himg = Wimg = 0
                image_wh = torch.tensor(
                    [Wimg, Himg], device=device, dtype=dtype,
                ).expand(bs, num_cams, 2).contiguous()
            else:
                image_wh = torch.zeros(bs, num_cams, 2, device=device, dtype=dtype)
        else:
            if not torch.is_tensor(image_wh):
                image_wh = torch.as_tensor(image_wh, device=device, dtype=dtype)
            image_wh = image_wh.to(device=device, dtype=dtype)
            if image_wh.dim() == 2:
                image_wh = image_wh.unsqueeze(0).expand(bs, num_cams, 2).contiguous()
        return image_wh

    @staticmethod
    def _reshape_projection_mat(projection_mat, bs, num_cams):
        if projection_mat is None:
            return None
        p = projection_mat
        if p.dim() == 3:
            p = p.view(bs, num_cams, 4, 4)
        elif p.dim() == 4 and p.shape[1] != num_cams:
            p = p.view(bs, num_cams, 4, 4)
        return p.float()

    # ------------------------------------------------------------------
    # SparseBEVOEHead aux_modules hook: after_decoder
    # ------------------------------------------------------------------
    def after_decoder(self, ctx, output):
        """Called at the end of ``SparseBEVOEHead.forward`` (post-decoder).

        Reads geometric / feature state from ``ctx``, runs the 2D
        refinement head, writes ``pred_2d_box`` / ``pred_2d_cls`` into
        the head's output dict. Stays a no-op during eval to skip the
        unused cost (2D head is auxiliary supervision only).
        """
        if not ctx.get('training', True):
            return

        anchor = ctx.get('anchor')
        anchor_embed = ctx.get('anchor_embed')
        feature_maps = ctx.get('feature_maps')
        projection_mat = ctx.get('projection_mat_raw')
        num_free_instance = ctx.get('num_free_instance')
        metas = ctx.get('metas', {})

        if (anchor is None or anchor_embed is None
                or feature_maps is None or projection_mat is None):
            return

        bs, num_anchor = anchor.shape[:2]
        feat_map = feature_maps[self.level_index]
        if feat_map.dim() == 5:
            num_cams = feat_map.shape[1]
        else:
            num_cams = feat_map.shape[0] // bs

        proj = self._reshape_projection_mat(projection_mat, bs, num_cams)
        anchor_xyz = anchor[..., :3].detach()
        xy_pixel, _ = self._project_anchor_center(anchor_xyz, proj)

        image_wh = self._infer_image_wh(
            metas, anchor.device, anchor.dtype, bs, num_cams,
        )

        per_cam_feat = self._sample_per_cam_features(
            feat_map, xy_pixel, image_wh,
        )

        feat = per_cam_feat + anchor_embed.unsqueeze(1)
        feat_bv = feat.contiguous().view(bs * num_cams, num_anchor, self.embed_dims)
        bbox_offsets = self.layers(feat_bv)
        prior_flat = xy_pixel.contiguous().view(bs * num_cams, num_anchor, 2)
        bbox_2d = self._bbox_decode(prior_flat, bbox_offsets)
        bbox_2d = bbox_2d.view(bs, num_cams, num_anchor, 4)

        if self.cls_layers is not None:
            cls_input = per_cam_feat.contiguous().view(
                bs * num_cams, num_anchor, self.embed_dims,
            )
            cls_logits = self.cls_layers(cls_input).view(
                bs, num_cams, num_anchor, self.num_cls,
            )
        else:
            cls_logits = bbox_2d.new_zeros(bs, num_cams, num_anchor, self.num_cls)

        if num_free_instance is not None:
            bbox_2d = bbox_2d[:, :, :num_free_instance, :]
            cls_logits = cls_logits[:, :, :num_free_instance, :]

        output['pred_2d_box'] = bbox_2d
        output['pred_2d_cls'] = cls_logits
        output['_refine2d_image_wh'] = image_wh
        output['_refine2d_proj'] = proj

    # ------------------------------------------------------------------
    # 2D target generation (project matched 3D GT corners → 2D bbox,
    # optionally replaced/augmented by real per-camera 2D GT)
    # ------------------------------------------------------------------
    @staticmethod
    def _box_iou_xyxy(boxes_a: torch.Tensor, boxes_b: torch.Tensor) -> torch.Tensor:
        """IoU between (M, 4) and (N, 4) tlbr boxes -> (M, N)."""
        if boxes_a.numel() == 0 or boxes_b.numel() == 0:
            return boxes_a.new_zeros(boxes_a.shape[0], boxes_b.shape[0])
        a_xy1 = boxes_a[:, None, :2]
        a_xy2 = boxes_a[:, None, 2:]
        b_xy1 = boxes_b[None, :, :2]
        b_xy2 = boxes_b[None, :, 2:]
        inter_xy1 = torch.maximum(a_xy1, b_xy1)
        inter_xy2 = torch.minimum(a_xy2, b_xy2)
        inter_wh = (inter_xy2 - inter_xy1).clamp(min=0)
        inter = inter_wh[..., 0] * inter_wh[..., 1]
        area_a = ((boxes_a[:, 2:] - boxes_a[:, :2]).clamp(min=0).prod(dim=1))
        area_b = ((boxes_b[:, 2:] - boxes_b[:, :2]).clamp(min=0).prod(dim=1))
        union = area_a[:, None] + area_b[None, :] - inter
        return torch.where(union > 0, inter / union.clamp(min=1e-6),
                           inter.new_zeros(()))

    @staticmethod
    def _unwrap_to_bv(x):
        """Normalize the GT container into ``list[B] of list[V] of Tensor``.

        The on-the-wire layout produced by ``argoverse2_dataset_t.
        union2one`` + ``PETRFormatBundle3D`` + DDP collate is

            list[B] of list[num_frame=1] of list[V] of Tensor[N_v, 4]

        i.e. there is a stale ``num_frame`` axis between B and V. We
        walk every batch element and peel any extra ``list[F] of list[V]``
        wrap by taking the last frame (queue_length=1 typically gives
        exactly one frame). Per-sample Tensor / ndarray leaves (no
        per-view split) are returned as-is so the per-view loop can
        wrap them itself. Logic mirrors ``Det2DHead._unwrap_to_bv``.
        """
        if x is None:
            return []
        if not isinstance(x, (list, tuple)):
            return [x]
        out = []
        for item in x:
            while (isinstance(item, (list, tuple))
                   and len(item) > 0
                   and isinstance(item[0], (list, tuple))):
                item = item[-1]
            out.append(item)
        return out

    def _resolve_real_gt(self, ctx):
        """Pull per-camera 2D GT lists from ctx['metas'].

        Returns ``None`` if not present. Otherwise a tuple
        ``(bboxes_per_view, labels_per_view)`` where each is
        ``list[B] of list[V] of Tensor`` (labels may be ``None``).
        Both are normalized through ``_unwrap_to_bv`` so the
        downstream SimOTA / IoU-real loops can iterate ``b, v``
        without worrying about queue-dim wrappers.
        """
        if ctx is None:
            return None
        metas = ctx.get('metas') if isinstance(ctx, dict) else None
        if metas is None:
            return None
        bboxes = metas.get(self.gt_bboxes_key)
        labels = metas.get(self.gt_labels_key)
        if bboxes is None:
            return None
        bboxes = self._unwrap_to_bv(bboxes)
        labels = self._unwrap_to_bv(labels) if labels is not None else None
        return bboxes, labels

    # ------------------------------------------------------------------
    # SimOTA dynamic-k assignment (ws-onemodel-dev style)
    # ------------------------------------------------------------------
    # The two helpers below are a direct port of ws-onemodel-dev's
    # ``SparseBEVOEHead._dynamic_k_matching`` / ``_assign_2d_simota``
    # (in their ``head.py``). The semantics are intentionally identical
    # so the ``real_simota`` mode here matches their assignment exactly:
    #   * full anchor pool participates (NOT filtered by the 3D matcher's
    #     ``mask_full``), so 2D supervision can reach anchors that 3D
    #     missed;
    #   * per-(batch, cam) dynamic k = clamp(topk-IoU.sum(), min=1);
    #   * top-k cheapest preds per GT are positives;
    #   * preds matched to >1 GT collapse to the cheapest one.
    # We extend their 1-class layout with optional multi-class labels
    # (``cls_target = num_cls`` for background, real label index for
    # positives) so the downstream ``loss_cls2d`` can stay multi-class.
    @staticmethod
    def _dynamic_k_matching(
        cost: torch.Tensor,
        pairwise_ious: torch.Tensor,
        num_gt: int,
        valid_mask: torch.Tensor,
        candidate_topk: int = 5,
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        """Per-cam SimOTA dynamic-k matcher.

        Mirrors ``Sparse4DHead.dynamic_k_matching`` (ws-onemodel-dev):
          * topk-IoU sum -> per-GT dynamic k
          * top-k cheapest preds per GT become candidates
          * any pred matched to >1 GT collapses to the cheapest one
          * fills ``valid_mask`` (in-place) with the final pred-side
            positive mask.

        Returns ``(matched_ious, matched_gt_inds)`` for the surviving
        positives (length = number of positives).
        """
        matching_matrix = torch.zeros_like(cost, dtype=torch.uint8)
        candidate_topk = min(candidate_topk, pairwise_ious.size(0))
        if candidate_topk == 0 or num_gt == 0:
            valid_mask[:] = False
            return cost.new_zeros((0,)), cost.new_zeros((0,), dtype=torch.long)
        topk_ious, _ = torch.topk(pairwise_ious, candidate_topk, dim=0)
        dynamic_ks = torch.clamp(topk_ious.sum(0).int(), min=1)
        for gt_idx in range(num_gt):
            k = int(dynamic_ks[gt_idx].item())
            if k <= 0:
                continue
            _, pos_idx = torch.topk(cost[:, gt_idx], k=k, largest=False)
            matching_matrix[pos_idx, gt_idx] = 1
        prior_match_gt_mask = matching_matrix.sum(1) > 1
        if prior_match_gt_mask.sum() > 0:
            _, cost_argmin = torch.min(cost[prior_match_gt_mask, :], dim=1)
            matching_matrix[prior_match_gt_mask, :] = 0
            matching_matrix[prior_match_gt_mask, cost_argmin] = 1
        fg_mask_inboxes = matching_matrix.sum(1) > 0
        valid_mask[valid_mask.clone()] = fg_mask_inboxes
        matched_gt_inds = matching_matrix[fg_mask_inboxes, :].argmax(1)
        matched_ious = (matching_matrix * pairwise_ious).sum(1)[fg_mask_inboxes]
        return matched_ious, matched_gt_inds

    def _assign_2d_simota_real(
        self,
        pred_box2d: torch.Tensor,
        real_gt_bboxes,
        real_gt_labels,
    ) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
        """Per (batch, cam) SimOTA assignment vs real 2D GT.

        Args:
            pred_box2d: ``(B, V, A, 4)`` decoded ``[x1, y1, x2, y2]``.
            real_gt_bboxes: ``list[B] of list[V] of (N_cam, >=4)`` real
                per-cam 2D GT (extra trailing channel optionally treated
                as a valid flag, matching the Sparse4D layout).
            real_gt_labels: ``list[B] of list[V] of (N_cam,)`` real
                per-cam class labels. May be ``None`` (single-class
                objectness fallback: every positive gets class index 0).

        Returns:
            cls_target: ``(B, V, A)`` long. ``num_cls`` for negatives,
                real label index in ``[0, num_cls)`` for positives.
            valid_2d: ``(B, V, A)`` bool. True at positive positions.
            box_pred_pos: ``(M, 4)`` matched predictions.
            box_target_pos: ``(M, 4)`` matched GT boxes.
        """
        B, V, A, _ = pred_box2d.shape
        device = pred_box2d.device
        cls_target = pred_box2d.new_full(
            (B, V, A), self.num_cls, dtype=torch.long,
        )
        valid_2d = torch.zeros((B, V, A), dtype=torch.bool, device=device)
        box_pred_pos: List[torch.Tensor] = []
        box_target_pos: List[torch.Tensor] = []
        if real_gt_bboxes is None:
            return (
                cls_target, valid_2d,
                pred_box2d.new_zeros((0, 4)),
                pred_box2d.new_zeros((0, 4)),
            )
        for b in range(B):
            bb_v = real_gt_bboxes[b] if b < len(real_gt_bboxes) else None
            lb_v = (
                real_gt_labels[b]
                if (real_gt_labels is not None and b < len(real_gt_labels))
                else None
            )
            # Tolerate the same ``list[B] of Tensor`` collapse ws's
            # version handles (a single concatenated tensor instead of
            # a per-view list).
            if isinstance(bb_v, torch.Tensor):
                bb_v = [bb_v]
            if isinstance(lb_v, torch.Tensor):
                lb_v = [lb_v]
            if bb_v is None:
                continue
            for v in range(V):
                if v >= len(bb_v):
                    continue
                gt = bb_v[v]
                lab = (
                    lb_v[v] if (lb_v is not None and v < len(lb_v)) else None
                )
                if gt is None:
                    continue
                if not torch.is_tensor(gt):
                    gt = torch.as_tensor(gt)
                if gt.numel() == 0:
                    continue
                gt = gt.to(device=device, dtype=pred_box2d.dtype)
                if gt.dim() == 1:
                    gt = gt.reshape(-1, 4)
                # Optional 5th column = valid flag (ws-style filter).
                if gt.shape[-1] > 4:
                    mask_flag = gt[:, 4] > 0
                    gt = gt[mask_flag]
                    if lab is not None and torch.is_tensor(lab) and lab.numel() > 0:
                        lab = lab.to(device=device)[mask_flag]
                if gt.shape[0] == 0:
                    continue
                gt_xyxy = gt[:, :4]
                preds = pred_box2d[b, v]
                valid_mask = torch.ones(
                    preds.shape[0], dtype=torch.bool, device=device,
                )
                pairwise_ious = bbox_overlaps(preds, gt_xyxy).clamp(min=0)
                cost = -torch.log(pairwise_ious + self.simota_eps)
                _, matched_gt_inds = self._dynamic_k_matching(
                    cost, pairwise_ious, gt_xyxy.shape[0], valid_mask,
                    candidate_topk=self.simota_topk,
                )
                if not valid_mask.any():
                    continue
                valid_2d[b, v] = valid_mask
                # Multi-class label assignment: real label if available,
                # else fallback to class 0 (single-class objectness).
                if lab is not None and torch.is_tensor(lab) and lab.numel() > 0:
                    lab_t = lab.to(device=device, dtype=torch.long).reshape(-1)
                    matched_lab = lab_t[matched_gt_inds].clamp(
                        min=0, max=self.num_cls - 1,
                    )
                    cls_target[b, v, valid_mask] = matched_lab
                else:
                    cls_target[b, v, valid_mask] = 0
                box_pred_pos.append(preds[valid_mask])
                box_target_pos.append(gt_xyxy[matched_gt_inds])
        if box_pred_pos:
            box_pred_pos_t = torch.cat(box_pred_pos, dim=0)
            box_target_pos_t = torch.cat(box_target_pos, dim=0)
        else:
            box_pred_pos_t = pred_box2d.new_zeros((0, 4))
            box_target_pos_t = pred_box2d.new_zeros((0, 4))
        return cls_target, valid_2d, box_pred_pos_t, box_target_pos_t

    def _apply_real_gt(self, box2d_target, valid, cls_target_2d_b,
                       ctx, bs, num_cams):
        """Replace / filter (box2d_target, valid) using per-cam real 2D GT.

        Match each currently-valid matched anchor's geometric projection
        box to the per-camera GT list by IoU. Behaviour controlled by
        ``self.gt_source``:

        * ``'real'``  : keep only anchors with IoU >= ``gt_match_iou_thr``,
                       replace their target with the matched real GT;
                       drop the rest (set valid=False).
        * ``'hybrid'``: replace target where IoU >= thr; keep geom target
                       otherwise.

        ``cls_target_2d_b`` (B, V, A) may be updated with real labels
        when available (only at matched positions).
        """
        gt = self._resolve_real_gt(ctx)
        if gt is None or self.gt_source == 'project':
            return box2d_target, valid, cls_target_2d_b
        bboxes_per_view, labels_per_view = gt

        new_target = box2d_target.clone()
        new_valid = valid.clone()
        new_cls = cls_target_2d_b.clone() if cls_target_2d_b is not None else None

        for b in range(bs):
            bb_v = bboxes_per_view[b] if (
                bboxes_per_view is not None and b < len(bboxes_per_view)
            ) else None
            lb_v = labels_per_view[b] if (
                labels_per_view is not None and b < len(labels_per_view)
            ) else None
            if isinstance(bb_v, torch.Tensor):
                bb_v = [bb_v]
            if isinstance(lb_v, torch.Tensor):
                lb_v = [lb_v]
            for v in range(num_cams):
                real_box = bb_v[v] if (bb_v is not None and v < len(bb_v)) else None
                real_lab = lb_v[v] if (lb_v is not None and v < len(lb_v)) else None
                valid_bv = valid[b, v]
                if not valid_bv.any():
                    continue
                if real_box is None or (
                    torch.is_tensor(real_box) and real_box.numel() == 0
                ):
                    if self.gt_source == 'real':
                        new_valid[b, v] = False
                    continue
                if not torch.is_tensor(real_box):
                    real_box = torch.as_tensor(real_box)
                real_box = real_box.to(
                    device=box2d_target.device, dtype=box2d_target.dtype
                ).reshape(-1, 4)
                idx = valid_bv.nonzero(as_tuple=True)[0]
                geom_valid = box2d_target[b, v, idx]
                iou = self._box_iou_xyxy(geom_valid, real_box)
                max_iou, argmax = iou.max(dim=1)
                ok = max_iou >= self.gt_match_iou_thr
                if ok.any():
                    matched = real_box[argmax[ok]]
                    new_target[b, v, idx[ok]] = matched
                    if new_cls is not None and real_lab is not None and (
                        torch.is_tensor(real_lab) and real_lab.numel() > 0
                    ):
                        real_lab_t = real_lab.to(
                            device=new_cls.device, dtype=new_cls.dtype
                        ).reshape(-1)
                        new_cls[b, v, idx[ok]] = real_lab_t[argmax[ok]]
                if self.gt_source == 'real':
                    bad = idx[~ok]
                    if bad.numel() > 0:
                        new_valid[b, v, bad] = False
        return new_target, new_valid, new_cls

    def _build_2d_targets(self, reg_target_full, mask_full,
                         projection_mat, image_wh):
        """For every matched 3D anchor, project its 3D corners to each
        cam and derive a (cam, anchor) 2D bbox target + visibility mask.

        Args:
            reg_target_full: (B, A, 10) encoded
                ``[x, y, z, log_w, log_l, log_h, sin_yaw, cos_yaw, vx, vy]``.
            mask_full: (B, A) bool — 3D matched anchors.
            projection_mat: (B, V, 4, 4) raw lidar2img.
            image_wh: (B, V, 2) (W, H) padded image size.

        Returns:
            box2d_target: (B, V, A, 4) tlbr in pixel coords (zeros where
                          invalid).
            valid:        (B, V, A) bool — matched anchor with >=4
                          corners in front of cam AND projected box
                          overlapping the image rect.
        """
        center = reg_target_full[..., 0:3]
        size = reg_target_full[..., 3:6].exp()
        sin_yaw = reg_target_full[..., 6:7]
        cos_yaw = reg_target_full[..., 7:8]
        corners = self._build_3d_corners(center, size, sin_yaw, cos_yaw)
        pix_xy, depth = self._project_corners(corners, projection_mat)

        bs, num_cams, num_anchor = pix_xy.shape[:3]
        in_front = depth > 0.5
        big_x = pix_xy.new_full(pix_xy.shape[:-1], float('inf'))[..., None]
        neg_big_x = -big_x
        x = torch.where(in_front[..., None], pix_xy[..., 0:1], big_x)
        y_min_in = torch.where(in_front[..., None], pix_xy[..., 1:2], big_x)
        x_max_in = torch.where(in_front[..., None], pix_xy[..., 0:1], neg_big_x)
        y_max_in = torch.where(in_front[..., None], pix_xy[..., 1:2], neg_big_x)
        tl_x = x.min(dim=-2).values.squeeze(-1)
        tl_y = y_min_in.min(dim=-2).values.squeeze(-1)
        br_x = x_max_in.max(dim=-2).values.squeeze(-1)
        br_y = y_max_in.max(dim=-2).values.squeeze(-1)
        box2d_target = torch.stack([tl_x, tl_y, br_x, br_y], dim=-1)

        n_in_front = in_front.sum(dim=-1)
        W = image_wh[..., 0:1].unsqueeze(2)
        H = image_wh[..., 1:2].unsqueeze(2)
        clip_tl_x = tl_x.clamp(min=0)
        clip_tl_y = tl_y.clamp(min=0)
        clip_br_x = br_x.clamp(max=W.squeeze(-1))
        clip_br_y = br_y.clamp(max=H.squeeze(-1))
        in_image = (clip_br_x > clip_tl_x) & (clip_br_y > clip_tl_y)
        valid_2d = (n_in_front >= 4) & in_image
        match_v = mask_full.unsqueeze(1).expand(-1, num_cams, -1)
        valid = valid_2d & match_v

        zero_box = box2d_target.new_zeros(box2d_target.shape)
        box2d_target = torch.where(valid[..., None], box2d_target, zero_box)
        return box2d_target, valid

    # ------------------------------------------------------------------
    # SparseBEVOEHead aux_modules hook: after_loss
    # ------------------------------------------------------------------
    def after_loss(self, ctx, output):
        """Called at the end of ``SparseBEVOEHead.loss``'s per-decoder
        loop, BEFORE the DN branch / DDP loss-key checksum.

        Computes the auxiliary 2D loss from this rank's last-layer
        targets and the 2D predictions stashed in the head's
        intermediate output dict. UNCONDITIONALLY emits the two loss
        keys (zero placeholder when no valid sample) so DDP key
        consistency is preserved by the module itself, not by the head.
        """
        last_idx = ctx.get('last_decoder_idx', 5)
        cls_target_full = ctx.get('last_cls_target_full')
        reg_target_full = ctx.get('last_reg_target_full')
        mask_full = ctx.get('last_mask_full')

        model_outs = ctx.get('model_outs', {})
        pred_2d_box = model_outs.get('pred_2d_box')
        pred_2d_cls = model_outs.get('pred_2d_cls')

        proj = model_outs.get('_refine2d_proj')
        image_wh = model_outs.get('_refine2d_image_wh')

        zero = None
        if pred_2d_box is not None:
            zero = pred_2d_box.sum() * 0.0
        elif reg_target_full is not None:
            zero = reg_target_full.sum() * 0.0
        else:
            zero = torch.tensor(0.0)

        # --- 'real_simota' branch: ws-style independent 2D assignment. -----
        # Skips the geometric-projection fallback AND the 3D matcher's
        # ``mask_full`` entirely. SimOTA runs over the full anchor pool
        # per (batch, cam) against the dataset's real 2D GT. cls / box
        # losses are normalised by the actual SimOTA positive count
        # (not the 3D-positive count) so the cls signal is no longer
        # diluted by 3D-positive-but-2D-unmatched anchors.
        if self.gt_source == 'real_simota':
            self._run_simota_branch(
                pred_2d_box, pred_2d_cls, ctx, last_idx, zero, output,
            )
            return

        if (pred_2d_box is None or pred_2d_cls is None
                or cls_target_full is None or reg_target_full is None
                or mask_full is None or proj is None or image_wh is None):
            output[f'loss_2d_box_{last_idx}'] = zero
            output[f'loss_2d_cls_{last_idx}'] = zero
            return

        bs, num_cams, num_anchor = pred_2d_box.shape[:3]
        if reg_target_full.shape[1] != num_anchor:
            reg_target_full = reg_target_full[:, :num_anchor]
            cls_target_full = cls_target_full[:, :num_anchor]
            mask_full = mask_full[:, :num_anchor]

        with torch.no_grad():
            box2d_target, valid_2d = self._build_2d_targets(
                reg_target_full.float(), mask_full,
                proj.view(bs, num_cams, 4, 4).float(), image_wh.float(),
            )

            cls_target_2d_b = cls_target_full[:, None, :].expand(
                -1, num_cams, -1,
            ).clone()
            if self.gt_source != 'project':
                box2d_target, valid_2d, cls_target_2d_b = self._apply_real_gt(
                    box2d_target, valid_2d, cls_target_2d_b,
                    ctx, bs, num_cams,
                )

        # Per-anchor class weight lookup — see class docstring for the
        # normalisation rationale (Option X: weighted avg_factor keeps
        # the overall refine2d loss magnitude stable, so doubling
        # every weight is a no-op and only RELATIVE weighting matters).
        # When ``class_loss_weights`` is unset the buffer is all-ones
        # and these multiplications are bit-identical to the un-weighted
        # baseline.
        num_cls = pred_2d_cls.shape[-1]
        cls_target_long = cls_target_2d_b.long()
        # ``cls_target_long`` is only used at mask_full=True positions
        # downstream, but we lookup over the full (B, V, A) tensor —
        # clamp guards against any sentinel values (e.g. ``num_cls``
        # for background) leaking out-of-bounds from upstream changes
        # to ``last_cls_target_full``. Positions with mask_full=False
        # get multiplied by 0 later anyway, so the clamped weight is
        # never observed there.
        per_anchor_cw = self._class_loss_weights[
            cls_target_long.clamp(0, num_cls - 1)
        ]

        if self.loss_bbox2d is not None and valid_2d.any():
            pos_pred = pred_2d_box[valid_2d]
            pos_tgt = box2d_target[valid_2d]
            pos_w = per_anchor_cw[valid_2d]
            # Weighted denominator (sum of per-positive class weights,
            # DDP-averaged) preserves the loss magnitude vs the
            # un-weighted baseline when all weights are 1.
            num_pos = max(_reduce_mean(pos_w.sum().float()), 1.0)
            box_loss = self.loss_bbox2d(pos_pred, pos_tgt, weight=pos_w)
            if isinstance(box_loss, dict):
                box_loss = sum(box_loss.values())
            box_loss = box_loss / num_pos
        else:
            box_loss = zero
        output[f'loss_2d_box_{last_idx}'] = (
            torch.nan_to_num(box_loss) * self.loss_weight
        )

        if self.loss_cls2d is not None and mask_full.any():
            cls_target_2d = cls_target_full.new_full(
                (bs, num_cams, num_anchor), num_cls, dtype=torch.long,
            )
            cls_target_2d = torch.where(
                valid_2d, cls_target_long, cls_target_2d,
            )
            # cls_w = (3D-positive mask) * (per-class weight). Positions
            # with mask_full=False contribute 0 (background placeholder
            # target wouldn't see gradient anyway).
            cls_w = (
                mask_full[:, None, :].expand(-1, num_cams, -1).float()
                * per_anchor_cw
            )
            avg_factor = max(
                _reduce_mean(cls_w.sum().float()), 1.0,
            )
            cls_loss = self.loss_cls2d(
                pred_2d_cls.flatten(end_dim=2),
                cls_target_2d.flatten().long(),
                weight=cls_w.flatten(),
                avg_factor=avg_factor,
            )
            if isinstance(cls_loss, dict):
                cls_loss = sum(cls_loss.values())
        else:
            cls_loss = zero
        output[f'loss_2d_cls_{last_idx}'] = (
            torch.nan_to_num(cls_loss) * self.loss_weight
        )

    # ------------------------------------------------------------------
    # 'real_simota' branch implementation
    # ------------------------------------------------------------------
    def _run_simota_branch(
        self, pred_2d_box, pred_2d_cls, ctx, last_idx, zero, output,
    ):
        """SimOTA-only branch for ``gt_source='real_simota'``.

        Bypasses the geometric-projection target builder and the 3D
        matcher's ``mask_full``. Loss normalisation uses the actual
        SimOTA-matched positive count (not the 3D-positive count), so
        the cls signal isn't diluted by 3D-positive-but-2D-unmatched
        anchors. DDP loss-key invariant is still preserved: both keys
        are always emitted (zero placeholder when no pred / no GT).
        """
        if pred_2d_box is None or pred_2d_cls is None:
            output[f'loss_2d_box_{last_idx}'] = zero
            output[f'loss_2d_cls_{last_idx}'] = zero
            return

        gt = self._resolve_real_gt(ctx)
        if gt is None:
            output[f'loss_2d_box_{last_idx}'] = zero
            output[f'loss_2d_cls_{last_idx}'] = zero
            return
        real_gt_bboxes, real_gt_labels = gt

        # NOTE: SimOTA assignment is NOT wrapped in ``torch.no_grad()``.
        # ws-onemodel-dev runs it in grad mode too: the matching path
        # (dynamic-k topk, argmin) only produces int / bool tensors, so
        # gradient naturally stops there, while ``preds[valid_mask]``
        # still has to preserve the grad on ``pred_2d_box`` so the box
        # IoU loss can back-prop through the matched predictions.
        (
            cls_target_2d, valid_2d,
            box_pred_pos, box_target_pos,
        ) = self._assign_2d_simota_real(
            pred_2d_box.float(),
            real_gt_bboxes,
            real_gt_labels,
        )

        num_pos_2d = max(
            _reduce_mean(
                torch.tensor(
                    float(box_pred_pos.shape[0]),
                    device=pred_2d_box.device,
                )
            ),
            1.0,
        )

        if self.loss_bbox2d is not None and box_pred_pos.shape[0] > 0:
            # bbox_overlaps inside IoULoss expects tlbr; both inputs
            # are tlbr by construction (decoded above + ws_gt is xyxy).
            box_loss = self.loss_bbox2d(box_pred_pos, box_target_pos)
            if isinstance(box_loss, dict):
                box_loss = sum(box_loss.values())
            box_loss = box_loss / num_pos_2d
        else:
            box_loss = zero
        output[f'loss_2d_box_{last_idx}'] = (
            torch.nan_to_num(box_loss) * self.loss_weight
        )

        if self.loss_cls2d is not None:
            # ``cls_target_2d`` is (B, V, A) long with ``num_cls`` at
            # background positions and real label index at positives.
            # ``pred_2d_cls`` is (B, V, A, num_cls); flatten the spatial
            # dims and let CE-sigmoid / FocalLoss compute per-class BCE.
            # No per-position ``weight`` is passed: every anchor in
            # every cam is a SimOTA candidate, with avg_factor scaled
            # by the actual matched count. This matches the ws-style
            # ``loss_cls2d / num_pos_2d`` normalisation.
            cls_loss = self.loss_cls2d(
                pred_2d_cls.flatten(end_dim=2),
                cls_target_2d.flatten().long(),
                avg_factor=num_pos_2d,
            )
            if isinstance(cls_loss, dict):
                cls_loss = sum(cls_loss.values())
        else:
            cls_loss = zero
        output[f'loss_2d_cls_{last_idx}'] = (
            torch.nan_to_num(cls_loss) * self.loss_weight
        )
